[package]
name = "patina"
version = "0.1.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]
license = "MIT"
edition = "2018"
description = "HDR image viewer"
homepage = "https://github.com/mandeep/patina"
repository = "https://github.com/mandeep/patina"
documentation = "https://github.com/mandeep/patina"

[dependencies]
image2 = "0.11.3"
pixels = "0.0.2"
winit = "0.20.0-alpha5"
winit_input_helper = "0.4.0-alpha4"

[profile.dev]
opt-level = 3
debug = true
